const BASE='https://rawusa-rapid.vercel.app/rescuer'

Deno.serve((req:Request)=>{
  const u=new URL(req.url)
  const teamCode=(u.searchParams.get('team_code')||'').trim()
  const target=BASE+(teamCode?'?team_code='+encodeURIComponent(teamCode):'')
  const ua=req.headers.get('user-agent')||''
  const inApp=/WhatsApp|FBAN|FBAV|FB_IAB|Instagram|Messenger|Line\//i.test(ua)
  if(!inApp)return Response.redirect(target,302)
  const androidIntent='intent://rawusa-rapid.vercel.app/rescuer'+(teamCode?'?team_code='+encodeURIComponent(teamCode):'')+'#Intent;scheme=https;action=android.intent.action.VIEW;end'
  const html=`<!doctype html><html><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1,viewport-fit=cover"><meta name="theme-color" content="#078346"><title>Nepal Scouts Rescue Registration</title><style>*{box-sizing:border-box}body{margin:0;font-family:Arial,sans-serif;background:#f3f7f4;color:#17211b}.wrap{max-width:560px;margin:auto;padding:20px}.card{background:#fff;border:1px solid #dce8e0;border-radius:16px;padding:20px;margin-top:8vh;text-align:center}.logo{width:92px;height:92px;object-fit:contain}.btn{display:block;width:100%;padding:14px;border:0;border-radius:10px;background:#078346;color:#fff;font-weight:900;font-size:17px;text-decoration:none;margin:14px 0}.secondary{background:#edf4ef;color:#244234}.warn{background:#fff8e1;border:1px solid #ffe082;border-radius:10px;padding:12px;text-align:left;line-height:1.45}.small{font-size:13px;color:#637169;line-height:1.45}</style></head><body><main class="wrap"><section class="card"><img class="logo" src="https://fkxbohbrfotbwmqalzyw.supabase.co/functions/v1/scout-logo" alt="Nepal Scouts"><h2>Nepal Scouts Rescue</h2>${teamCode?`<div class="small">Team code <b>${teamCode.replace(/[<>&"]/g,'')}</b> will be filled automatically.</div>`:''}<div class="warn"><b>Open this registration in your phone browser.</b><br>Do not complete rescue registration inside WhatsApp, Facebook, Messenger, Instagram or another in-app browser. Location permission and tracking may be interrupted there.</div><a id="openBrowser" class="btn" href="${target}">Open in Default Browser</a><button id="copy" class="btn secondary">Copy Registration Link</button><div class="small">If the button does not open your browser, use the app menu (⋮ or Share), choose <b>Open in browser</b>, then allow precise location when Nepal Scouts Rescue asks.</div></section></main><script>const target=${JSON.stringify(target)},intent=${JSON.stringify(androidIntent)};if(/Android/i.test(navigator.userAgent||''))document.getElementById('openBrowser').href=intent;document.getElementById('copy').onclick=async()=>{try{await navigator.clipboard.writeText(target);alert('Registration link copied.')}catch{prompt('Copy this link:',target)}}</script></body></html>`
  return new Response(html,{headers:{'content-type':'text/html; charset=utf-8','cache-control':'no-store'}})
})
