import{useCallback,useEffect,useMemo,useRef,useState}from'react';
import{CircleMarker,LayersControl,MapContainer,Popup,Polyline,TileLayer}from'react-leaflet';
import'leaflet/dist/leaflet.css';
import{Activity,AlertTriangle,Battery,CheckCircle2,Cloud,CloudOff,LogOut,Map as MapIcon,MessageCircle,Navigation,RefreshCw,Shield,UserRound,Wifi,WifiOff}from'lucide-react';
import{SosHoldButton}from'../components/SosHoldButton';
import{getQueue,putQueue,removeQueue}from'../data/queueRepository';
import type{QueueKind,QueueRecord}from'../domain/types';
import{checkin,clearDeviceToken,deviceToken,loginRescuer,markMessage,registerRescuer,rescuer,rescuerStatus,sendRescuerMessage,updateProfile,uploadPhoto}from'./api';
import type{LivePosition,OperationalStatus,RescuerStatus}from'./types';
type Screen='home'|'mission'|'map'|'checkin'|'messages'|'sos'|'activity'|'profile'|'tracking'|'sync';
const labels:Record<string,string>={available:'Available',alerted:'Alerted',en_route:'En route',on_mission:'On mission',returning:'Returning',off_duty:'Off duty',safe_confirmed:'SAFE confirmed',safe_due:'SAFE due',safe_overdue:'SAFE overdue',sos:'SOS'};
const active=(s?:OperationalStatus)=>s==='on_mission'||s==='returning';
function rec(kind:QueueKind,payload:Record<string,unknown>):QueueRecord{return{id:crypto.randomUUID(),kind,capturedAt:new Date().toISOString(),syncState:'QUEUED',attempts:0,payload:{...payload,client_event_id:payload.client_event_id||crypto.randomUUID()}}}
async function batteryPct(){try{const nav=navigator as Navigator&{getBattery?:()=>Promise<{level:number}>};return nav.getBattery?Math.round((await nav.getBattery()).level*100):undefined}catch{return undefined}}
export default function RescuerLiveApp(){
 const[status,setStatus]=useState<RescuerStatus|null>(null),[screen,setScreen]=useState<Screen>('home'),[queue,setQueue]=useState<QueueRecord[]>([]),[notice,setNotice]=useState(''),[busy,setBusy]=useState(false),[online,setOnline]=useState(navigator.onLine),[gpsError,setGpsError]=useState(''),[route,setRoute]=useState<LivePosition[]>([]),watch=useRef<number|null>(null),syncing=useRef(false);
 const refresh=useCallback(async()=>{if(!deviceToken())return;try{const s=await rescuerStatus();setStatus(s)}catch(e){setNotice(e instanceof Error?e.message:'Could not refresh status')}},[]);
 useEffect(()=>{getQueue().then(setQueue).catch(()=>setNotice('Offline storage unavailable'));if(deviceToken())void refresh();const net=()=>{setOnline(navigator.onLine);if(navigator.onLine)void flush()};addEventListener('online',net);addEventListener('offline',net);return()=>{removeEventListener('online',net);removeEventListener('offline',net)}},[refresh]);
 useEffect(()=>{if(!deviceToken())return;const id=setInterval(()=>void refresh(),30000);return()=>clearInterval(id)},[refresh]);
 const persist=useCallback(async(kind:QueueKind,payload:Record<string,unknown>,message:string)=>{const r=rec(kind,payload);await putQueue(r);setQueue(q=>[...q,r]);setNotice(message);return r},[]);
 const flush=useCallback(async()=>{if(!navigator.onLine||syncing.current||!deviceToken())return;syncing.current=true;try{const items=await getQueue();for(const item of items){try{const p={...item.payload,client_event_id:item.payload.client_event_id||item.id};if(item.kind==='GPS')await rescuer({action:'location',event:'location',points:[p]});else if(item.kind==='CHECK_IN')await checkin(p);else if(item.kind==='SOS')await rescuer({action:'sos',event:'sos',...p});else if(item.kind==='MEDIA')await uploadPhoto(p);else await rescuer(p);await removeQueue(item.id)}catch(e){const failed={...item,syncState:'FAILED' as const,attempts:item.attempts+1,lastError:e instanceof Error?e.message:'Sync failed'};await putQueue(failed);break}}setQueue(await getQueue());await refresh()}finally{syncing.current=false}},[refresh]);
 useEffect(()=>{if(online&&queue.length)void flush()},[online,queue.length,flush]);
 useEffect(()=>{const should=Boolean(status&&status.approval_status==='approved'&&active(status.operational_status));if(!should){if(watch.current!=null)navigator.geolocation.clearWatch(watch.current);watch.current=null;return}if(watch.current!=null)return;if(!('geolocation'in navigator)){setGpsError('Location is not supported on this device');return}watch.current=navigator.geolocation.watchPosition(async pos=>{setGpsError('');const p:LivePosition={latitude:pos.coords.latitude,longitude:pos.coords.longitude,accuracy:pos.coords.accuracy,captured_at:new Date(pos.timestamp).toISOString(),battery:await batteryPct()};setRoute(r=>[...r.slice(-499),p]);const q=rec('GPS',{...p,recorded_at:p.captured_at,event_type:'location',offline:!navigator.onLine});await putQueue(q);setQueue(await getQueue());if(navigator.onLine)void flush()},err=>setGpsError(err.code===1?'GPS permission denied':err.message),{enableHighAccuracy:true,maximumAge:10000,timeout:20000});return()=>{if(watch.current!=null)navigator.geolocation.clearWatch(watch.current);watch.current=null}},[status?.approval_status,status?.operational_status,flush]);
 async function queuedAction(event:string,next?:OperationalStatus){setBusy(true);try{await persist('EVENT',{action:event,event,captured_at:new Date().toISOString()},navigator.onLine?'Action saved — sending':'Action saved — queued offline');if(navigator.onLine)await flush();if(next)setStatus(s=>s?{...s,operational_status:next}:s)}finally{setBusy(false)}}
 async function safe(){const p=status?.last_position||route.at(-1);await persist('EVENT',{action:'safe',event:'safe',captured_at:new Date().toISOString(),...(p||{}),battery:await batteryPct()},navigator.onLine?'SAFE saved — sending':'SAFE saved — queued offline');if(navigator.onLine)await flush()}
 async function sos(){const p=status?.last_position||route.at(-1);await persist('SOS',{action:'sos',event:'sos',created_at:new Date().toISOString(),...(p||{}),battery:await batteryPct()},navigator.onLine?'SOS saved locally — sending now':'SOS SAVED LOCALLY — waiting for network');setScreen('sos');if(navigator.onLine)await flush()}
 function logout(){if(watch.current!=null)navigator.geolocation.clearWatch(watch.current);clearDeviceToken();setStatus(null);setScreen('home');setNotice('Signed out')}
 if(!status)return <Auth onReady={s=>{setStatus(s);void refresh()}} notice={notice}/>;
 const gpsAge=status.last_position?Math.max(0,Math.round((Date.now()-new Date(status.last_position.captured_at).getTime())/1000)):null;
 const health=gpsError?'LOCATION OFF':active(status.operational_status)?gpsAge==null?'TRACKING LOST':gpsAge<=180?'GPS LIVE':gpsAge<=600?'GPS DELAYED':'TRACKING LOST':'TRACKING STANDBY';
 const views:Record<Screen,React.ReactNode>={home:<Home s={status} health={health} gpsAge={gpsAge} queued={queue.length} go={setScreen} act={queuedAction} safe={safe} sos={sos} busy={busy}/>,mission:<Mission s={status} act={queuedAction}/>,map:<LiveMap status={status} route={route}/>,checkin:<CheckIn s={status} persist={persist} flush={flush}/>,messages:<Messages s={status} refresh={refresh}/>,sos:<Sos s={status} online={online}/>,activity:<ActivityView queue={queue}/>,profile:<Profile s={status} refresh={refresh}/>,tracking:<Tracking s={status} health={health} gpsAge={gpsAge} gpsError={gpsError} queued={queue.filter(q=>q.kind==='GPS').length}/>,sync:<Sync queue={queue} online={online} flush={flush}/>};
 return <div className="live-shell"><header className="live-top"><div><b>Nepal Scouts</b><span>RESCUE · FIELD UNIT</span></div><button onClick={logout}><LogOut size={17}/> Logout</button></header>{notice&&<div className="live-notice">{notice}</div>}<main>{views[screen]}</main><nav className="live-nav"><Nav icon={<Navigation/>} text="Home" on={()=>setScreen('home')} active={screen==='home'}/><Nav icon={<MapIcon/>} text="Map" on={()=>setScreen('map')} active={screen==='map'}/><Nav icon={<Activity/>} text="Activity" on={()=>setScreen('activity')} active={screen==='activity'}/><Nav icon={<UserRound/>} text="Profile" on={()=>setScreen('profile')} active={screen==='profile'}/></nav></div>
}
function Auth({onReady,notice}:{onReady:(s:RescuerStatus)=>void;notice:string}){const[mode,setMode]=useState<'login'|'register'>('login'),[phone,setPhone]=useState(''),[pin,setPin]=useState(''),[name,setName]=useState(''),[teamCode,setTeamCode]=useState(''),[error,setError]=useState(''),[busy,setBusy]=useState(false);async function submit(){setBusy(true);setError('');try{const d=mode==='login'?await loginRescuer(phone,pin):await registerRescuer({team_code:teamCode,name,phone,pin});onReady(d as RescuerStatus)}catch(e){setError(e instanceof Error?e.message:'Sign in failed')}finally{setBusy(false)}}return <div className="auth-page"><section className="auth-card"><div className="auth-mark">NS</div><p className="eyebrow">NEPAL SCOUTS RESCUE</p><h1>{mode==='login'?'Rescuer Login':'Register Device'}</h1><p>Use the approved phone number and rescuer code. Location starts only during an approved active mission.</p>{mode==='register'&&<><label>Name<input value={name} onChange={e=>setName(e.target.value)} autoComplete="name"/></label><label>Team code<input value={teamCode} onChange={e=>setTeamCode(e.target.value)}/></label></>}<label>Phone<input value={phone} onChange={e=>setPhone(e.target.value)} inputMode="tel" autoComplete="tel"/></label><label>Rescuer code<input value={pin} onChange={e=>setPin(e.target.value)} inputMode="numeric" type="password" autoComplete="current-password"/></label>{(error||notice)&&<div className="error-box">{error||notice}</div>}<button className="primary" disabled={busy||!phone||pin.length<4} onClick={submit}>{busy?'Please wait…':mode==='login'?'Sign in':'Register'}</button><button className="linkbtn" onClick={()=>setMode(mode==='login'?'register':'login')}>{mode==='login'?'New rescuer/device? Register':'Already registered? Sign in'}</button></section></div>}
function Home({s,health,gpsAge,queued,go,act,safe,sos,busy}:{s:RescuerStatus;health:string;gpsAge:number|null;queued:number;go:(x:Screen)=>void;act:(e:string,n?:OperationalStatus)=>Promise<void>;safe:()=>Promise<void>;sos:()=>Promise<void>;busy:boolean}){const name=s.profile?.rescuer_name||s.rescuer_name;return <><section className="field-id">{s.profile?.profile_photo_data_url?<img src={s.profile.profile_photo_data_url}/>:<div className="avatar">{name.split(/\s+/).map(x=>x[0]).join('').slice(0,2)}</div>}<div><span>{s.team?.name||'Rescue Team'}</span><h1>{name}</h1><p>{s.approval_status==='approved'?'Approved device':s.approval_status.toUpperCase()}</p></div></section><section className="status-row"><Status label="Operational" value={labels[s.operational_status]}/><Status label="Safety" value={labels[s.safety_status]} danger={s.safety_status==='safe_overdue'||s.safety_status==='sos'}/></section><button className={`track-banner ${health.includes('LOST')||health.includes('OFF')?'danger':health.includes('DELAYED')?'warn':'ok'}`} onClick={()=>go('tracking')}><span className="dot"/><div><b>{health}</b><small>{gpsAge==null?'No current GPS point':`Last GPS ${gpsAge}s ago`} · {queued} queued</small></div>{navigator.onLine?<Wifi/>:<WifiOff/>}</button><section className="mission-card" onClick={()=>go('mission')}><span>CURRENT ASSIGNMENT</span><h2>{s.assignment?.incident_name||s.assignment?.incident_id||'No active assignment'}</h2><p>{s.assignment?.area||'Command has not assigned an area yet.'}</p><b>{s.assignment?.task||''}</b></section><div className="five-actions"><button className="start" disabled={busy||s.approval_status!=='approved'} onClick={()=>s.operational_status==='available'||s.operational_status==='alerted'?act('en_route','en_route'):s.operational_status==='en_route'?act('start','on_mission'):s.operational_status==='on_mission'?act('returning','returning'):act('end','off_duty')}><Navigation/><b>{s.operational_status==='en_route'?'Start Mission':s.operational_status==='on_mission'?'Returning':s.operational_status==='returning'?'End Mission':'En Route'}</b></button><button onClick={()=>go('map')}><MapIcon/><b>Map</b></button><button onClick={()=>go('checkin')}><CheckCircle2/><b>Check In</b></button><button onClick={()=>go('messages')}><MessageCircle/><b>Message</b></button></div><button className="safe-live" disabled={!active(s.operational_status)} onClick={safe}><Shield/><span><b>I AM SAFE</b><small>Resets safety timer only</small></span></button><SosHoldButton disabled={s.approval_status!=='approved'} onConfirm={()=>void sos()}/><div className="utility-row"><button onClick={()=>go('sync')}><Cloud/>Offline Sync · {queued}</button><button onClick={()=>go('tracking')}><Battery/>Tracking & Privacy</button></div></>}
function Mission({s,act}:{s:RescuerStatus;act:(e:string,n?:OperationalStatus)=>Promise<void>}){const a=s.assignment;return <Page title="Mission"><Card><Detail k="Incident" v={a?.incident_name||a?.incident_id||'Not assigned'}/><Detail k="Team" v={s.team?.name||'—'}/><Detail k="Area" v={a?.area||'—'}/><Detail k="Task" v={a?.task||'—'}/><Detail k="Meeting point" v={a?.meeting_point||'—'}/><Detail k="Safe route" v={a?.safe_route||'—'}/><Detail k="Operational" v={labels[s.operational_status]}/><Detail k="Safety" v={labels[s.safety_status]}/></Card><div className="stack">{s.operational_status==='alerted'&&<button className="primary" onClick={()=>act('en_route','en_route')}>Accept · En Route</button>}{s.operational_status==='en_route'&&<button className="primary" onClick={()=>act('start','on_mission')}>Start Mission</button>}{s.operational_status==='on_mission'&&<button className="amber" onClick={()=>act('returning','returning')}>Returning</button>}{s.operational_status==='returning'&&<button onClick={()=>act('end','off_duty')}>End Mission & Stop Tracking</button>}</div></Page>}
function LiveMap({status,route}:{status:RescuerStatus;route:LivePosition[]}){const p=route.at(-1)||status.last_position;const center:[number,number]=p?[p.latitude,p.longitude]:[27.7172,85.324];const line=(route.length?route:p?[p]:[]).map(x=>[x.latitude,x.longitude]as[number,number]);return <Page title="Operational Map"><div className="live-map"><MapContainer center={center} zoom={15} scrollWheelZoom><TileLayer attribution="&copy; OpenStreetMap contributors" url="https://{s}.tile.openstreetmap.org/{z}/{x}/{y}.png"/><LayersControl position="topright"><LayersControl.Overlay checked name="My route">{line.length>1&&<Polyline positions={line}/>}</LayersControl.Overlay><LayersControl.Overlay checked name="My location">{p&&<CircleMarker center={[p.latitude,p.longitude]} radius={9}><Popup>My latest GPS · ±{Math.round(p.accuracy)}m</Popup></CircleMarker>}</LayersControl.Overlay></LayersControl></MapContainer></div><p className="muted">Embedded and fullscreen operational maps use OpenStreetMap. No unverified team/hazard points are fabricated.</p></Page>}
function CheckIn({s,persist,flush}:{s:RescuerStatus;persist:(k:QueueKind,p:Record<string,unknown>,m:string)=>Promise<QueueRecord>;flush:()=>Promise<void>}){const[type,setType]=useState('Reached location'),[note,setNote]=useState(''),[fileState,setFileState]=useState('');const opts=['Reached location','Need medical','Need transport','Need food/water','Area searched','Victim found','Custom note'];async function submit(){const p=s.last_position||{};await persist('CHECK_IN',{action:'checkin',type,note,assignment_id:s.assignment?.id,captured_at:new Date().toISOString(),...p},navigator.onLine?'Check-in saved — sending':'Check-in saved offline');if(navigator.onLine)await flush();setNote('')}async function file(f:File){if(!f.type.startsWith('image/')){setFileState('Video requires the native/storage media phase; photo evidence is supported now.');return}if(f.size>550000){setFileState('Photo is too large for the current field channel. Choose a smaller/compressed image.');return}const data=await new Promise<string>((ok,no)=>{const r=new FileReader();r.onload=()=>ok(String(r.result));r.onerror=()=>no(r.error);r.readAsDataURL(f)});await persist('MEDIA',{action:'mission_photo',photo_data_url:data,caption:type,latitude:s.last_position?.latitude,longitude:s.last_position?.longitude,accuracy:s.last_position?.accuracy,captured_at:new Date(f.lastModified||Date.now()).toISOString()},navigator.onLine?'Evidence saved — sending':'Evidence saved offline');setFileState('Evidence safely stored.');if(navigator.onLine)await flush()}return <Page title="Quick Check-In"><div className="choice-grid">{opts.map(o=><button key={o} className={type===o?'selected':''} onClick={()=>setType(o)}>{o}</button>)}</div><textarea value={note} onChange={e=>setNote(e.target.value)} placeholder="Field note"/><button className="primary" onClick={submit}>Submit Check-In</button><label className="file-btn">Add photo evidence<input type="file" accept="image/*" capture="environment" onChange={e=>e.target.files?.[0]&&void file(e.target.files[0])}/></label>{fileState&&<p>{fileState}</p>}</Page>}
function Messages({s,refresh}:{s:RescuerStatus;refresh:()=>Promise<void>}){const[text,setText]=useState(''),[tab,setTab]=useState<'command'|'team'>('command');const msgs=(s.messages||[]).filter(m=>tab==='team'?Boolean(m.team_id):true);async function read(id:string,ack=false){await markMessage(id,ack);await refresh()}async function send(){if(!text.trim())return;await sendRescuerMessage(text.trim());setText('');await refresh()}return <Page title="Messages"><div className="tabs"><button className={tab==='command'?'active':''} onClick={()=>setTab('command')}>Command</button><button className={tab==='team'?'active':''} onClick={()=>setTab('team')}>Team</button></div>{msgs.map(m=><article key={m.id} className={`message ${m.priority==='urgent'||m.priority==='emergency'?'urgent':''}`}><b>{m.priority.toUpperCase()}</b><p>{m.message}</p><small>{new Date(m.created_at).toLocaleString()}</small><div>{!m.read_at&&<button onClick={()=>read(m.id)}>Mark read</button>}{!m.acknowledged_at&&(m.priority==='urgent'||m.priority==='emergency')&&<button className="primary" onClick={()=>read(m.id,true)}>Acknowledge</button>}</div></article>)}<textarea value={text} onChange={e=>setText(e.target.value)} placeholder="Message Command"/><button className="primary" onClick={send}>Send</button></Page>}
function Sos({s,online}:{s:RescuerStatus;online:boolean}){return <Page title="SOS Emergency"><section className="sos-panel"><AlertTriangle/><h2>{s.sos_status==='acknowledged'?'COMMAND ACKNOWLEDGED':s.sos_status==='resolved'?'SOS RESOLVED':'SOS RAISED'}</h2><p>{s.sos_status==='acknowledged'?'Command has acknowledged your SOS. Follow instructions and remain visible.':online?'Delivery is being retried until Command receives it.':'SOS is stored locally and will retry when network returns.'}</p><Detail k="Operational (unchanged)" v={labels[s.operational_status]}/><Detail k="Safety" v={labels[s.safety_status]}/></section></Page>}
function ActivityView({queue}:{queue:QueueRecord[]}){return <Page title="Activity & Pending Events">{queue.length===0?<Card><p>No unsynchronized field records.</p></Card>:queue.slice().reverse().map(q=><article className="event" key={q.id}><b>{q.kind}</b><span>{q.syncState}</span><small>{new Date(q.capturedAt).toLocaleString()}</small>{q.lastError&&<p>{q.lastError}</p>}</article>)}<p className="muted">Server activity remains immutable in Command. Pending local records remain here until confirmed by the server.</p></Page>}
function Profile({s,refresh}:{s:RescuerStatus;refresh:()=>Promise<void>}){const p=s.profile;const[address,setAddress]=useState(p?.address||''),[blood,setBlood]=useState(p?.blood_group||'');async function save(){await updateProfile({address,blood_group:blood});await refresh()}return <Page title="Rescuer Profile"><Card><Detail k="Name" v={p?.rescuer_name||s.rescuer_name}/><Detail k="Phone" v={p?.phone||s.phone||'—'}/><Detail k="Team" v={s.team?.name||'—'}/><Detail k="Device" v={s.approval_status}/><Detail k="District" v={p?.deployment_district||'—'}/><Detail k="Emergency" v={[p?.emergency_contact_name,p?.emergency_contact_phone].filter(Boolean).join(' · ')||'—'}/></Card><label>Address<input value={address} onChange={e=>setAddress(e.target.value)}/></label><label>Blood group<input value={blood} onChange={e=>setBlood(e.target.value)}/></label><button className="primary" onClick={save}>Save profile</button></Page>}
function Tracking({s,health,gpsAge,gpsError,queued}:{s:RescuerStatus;health:string;gpsAge:number|null;gpsError:string;queued:number}){return <Page title="Tracking & Privacy"><Card><Detail k="Tracking" v={active(s.operational_status)?'ON — approved active mission':'OFF — no active mission'}/><Detail k="Health" v={health}/><Detail k="Last GPS" v={gpsAge==null?'No GPS':`${gpsAge}s ago`}/><Detail k="Accuracy" v={s.last_position?`±${Math.round(s.last_position.accuracy)}m`:'—'}/><Detail k="Offline GPS queue" v={String(queued)}/>{gpsError&&<Detail k="Location warning" v={gpsError}/>}</Card><div className="privacy"><Shield/><p>GPS starts only while your approved mission is active/returning and stops when the mission ends or you log out. Browser/PWA background capture can still be suspended by the operating system.</p></div></Page>}
function Sync({queue,online,flush}:{queue:QueueRecord[];online:boolean;flush:()=>Promise<void>}){const counts=useMemo(()=>Object.fromEntries(['GPS','CHECK_IN','MEDIA','SOS','EVENT'].map(k=>[k,queue.filter(q=>q.kind===k).length])),[queue]);return <Page title="Offline Sync"><section className={`connect ${online?'ok':'warn'}`}>{online?<Cloud/>:<CloudOff/>}<div><b>{online?'Online':'Offline'}</b><p>{online?'Server delivery available.':'Field records stay safely on this device.'}</p></div></section><Card>{Object.entries(counts).map(([k,v])=><Detail key={k} k={k.replace('_',' ')} v={String(v)}/>)}</Card><button className="primary" disabled={!online||!queue.length} onClick={()=>void flush()}><RefreshCw/> Sync now</button></Page>}
function Page({title,children}:{title:string;children:React.ReactNode}){return <section className="live-page"><p className="eyebrow">NEPAL SCOUTS RESCUE</p><h1>{title}</h1>{children}</section>}function Card({children}:{children:React.ReactNode}){return <section className="live-card">{children}</section>}function Detail({k,v}:{k:string;v:string}){return <div className="detail"><span>{k}</span><b>{v}</b></div>}function Status({label,value,danger=false}:{label:string;value:string;danger?:boolean}){return <div><small>{label}</small><b className={danger?'red':''}>{value}</b></div>}function Nav({icon,text,on,active}:{icon:React.ReactNode;text:string;on:()=>void;active:boolean}){return <button className={active?'active':''} onClick={on}>{icon}<small>{text}</small></button>}
